package com.thorcompanion

/** Map group/number order from pokeemerald's data/maps/map_groups.json. */
object EmeraldMapCatalog {
    private val entries = mutableMapOf<Pair<Int, Int>, EmeraldMap>().apply {
        add(0, 0, "MAP_PETALBURG_CITY", "Petalburg City")
        add(0, 1, "MAP_SLATEPORT_CITY", "Slateport City")
        add(0, 2, "MAP_MAUVILLE_CITY", "Mauville City")
        add(0, 3, "MAP_RUSTBORO_CITY", "Rustboro City")
        add(0, 4, "MAP_FORTREE_CITY", "Fortree City")
        add(0, 5, "MAP_LILYCOVE_CITY", "Lilycove City")
        add(0, 6, "MAP_MOSSDEEP_CITY", "Mossdeep City")
        add(0, 7, "MAP_SOOTOPOLIS_CITY", "Sootopolis City")
        add(0, 8, "MAP_EVER_GRANDE_CITY", "Ever Grande City")
        add(0, 9, "MAP_LITTLEROOT_TOWN", "Littleroot Town")
        add(0, 10, "MAP_OLDALE_TOWN", "Oldale Town")
        add(0, 11, "MAP_DEWFORD_TOWN", "Dewford Town")
        add(0, 12, "MAP_LAVARIDGE_TOWN", "Lavaridge Town")
        add(0, 13, "MAP_FALLARBOR_TOWN", "Fallarbor Town")
        add(0, 14, "MAP_VERDANTURF_TOWN", "Verdanturf Town")
        add(0, 15, "MAP_PACIFIDLOG_TOWN", "Pacifidlog Town")
        add(0, 16, "MAP_ROUTE101", "Route 101")
        add(0, 17, "MAP_ROUTE102", "Route 102")
        add(0, 18, "MAP_ROUTE103", "Route 103")
        add(0, 19, "MAP_ROUTE104", "Route 104")
        add(0, 20, "MAP_ROUTE105", "Route 105")
        add(0, 21, "MAP_ROUTE106", "Route 106")
        add(0, 22, "MAP_ROUTE107", "Route 107")
        add(0, 23, "MAP_ROUTE108", "Route 108")
        add(0, 24, "MAP_ROUTE109", "Route 109")
        add(0, 25, "MAP_ROUTE110", "Route 110")
        add(0, 26, "MAP_ROUTE111", "Route 111")
        add(0, 27, "MAP_ROUTE112", "Route 112")
        add(0, 28, "MAP_ROUTE113", "Route 113")
        add(0, 29, "MAP_ROUTE114", "Route 114")
        add(0, 30, "MAP_ROUTE115", "Route 115")
        add(0, 31, "MAP_ROUTE116", "Route 116")
        add(0, 32, "MAP_ROUTE117", "Route 117")
        add(0, 33, "MAP_ROUTE118", "Route 118")
        add(0, 34, "MAP_ROUTE119", "Route 119")
        add(0, 35, "MAP_ROUTE120", "Route 120")
        add(0, 36, "MAP_ROUTE121", "Route 121")
        add(0, 37, "MAP_ROUTE122", "Route 122")
        add(0, 38, "MAP_ROUTE123", "Route 123")
        add(0, 39, "MAP_ROUTE124", "Route 124")
        add(0, 40, "MAP_ROUTE125", "Route 125")
        add(0, 41, "MAP_ROUTE126", "Route 126")
        add(0, 42, "MAP_ROUTE127", "Route 127")
        add(0, 43, "MAP_ROUTE128", "Route 128")
        add(0, 44, "MAP_ROUTE129", "Route 129")
        add(0, 45, "MAP_ROUTE130", "Route 130")
        add(0, 46, "MAP_ROUTE131", "Route 131")
        add(0, 47, "MAP_ROUTE132", "Route 132")
        add(0, 48, "MAP_ROUTE133", "Route 133")
        add(0, 49, "MAP_ROUTE134", "Route 134")
        add(0, 50, "MAP_UNDERWATER_ROUTE124", "Underwater Route 124")
        add(0, 51, "MAP_UNDERWATER_ROUTE126", "Underwater Route 126")
        add(0, 52, "MAP_UNDERWATER_ROUTE127", "Underwater Route 127")
        add(0, 53, "MAP_UNDERWATER_ROUTE128", "Underwater Route 128")
        add(0, 54, "MAP_UNDERWATER_ROUTE129", "Underwater Route 129")
        add(0, 55, "MAP_UNDERWATER_ROUTE105", "Underwater Route 105")
        add(0, 56, "MAP_UNDERWATER_ROUTE125", "Underwater Route 125")
        add(1, 0, "MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F", "Littleroot Town Brendans House 1F")
        add(1, 1, "MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F", "Littleroot Town Brendans House 2F")
        add(1, 2, "MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F", "Littleroot Town Mays House 1F")
        add(1, 3, "MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F", "Littleroot Town Mays House 2F")
        add(1, 4, "MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB", "Littleroot Town Professor Birchs Lab")
        add(2, 0, "MAP_OLDALE_TOWN_HOUSE1", "Oldale Town House 1")
        add(2, 1, "MAP_OLDALE_TOWN_HOUSE2", "Oldale Town House 2")
        add(2, 2, "MAP_OLDALE_TOWN_POKEMON_CENTER_1F", "Oldale Town Pokemon Center 1F")
        add(2, 3, "MAP_OLDALE_TOWN_POKEMON_CENTER_2F", "Oldale Town Pokemon Center 2F")
        add(2, 4, "MAP_OLDALE_TOWN_MART", "Oldale Town Mart")
        add(3, 0, "MAP_DEWFORD_TOWN_HOUSE1", "Dewford Town House 1")
        add(3, 1, "MAP_DEWFORD_TOWN_POKEMON_CENTER_1F", "Dewford Town Pokemon Center 1F")
        add(3, 2, "MAP_DEWFORD_TOWN_POKEMON_CENTER_2F", "Dewford Town Pokemon Center 2F")
        add(3, 3, "MAP_DEWFORD_TOWN_GYM", "Dewford Town Gym")
        add(3, 4, "MAP_DEWFORD_TOWN_HALL", "Dewford Town Hall")
        add(3, 5, "MAP_DEWFORD_TOWN_HOUSE2", "Dewford Town House 2")
        add(4, 0, "MAP_LAVARIDGE_TOWN_HERB_SHOP", "Lavaridge Town Herb Shop")
        add(4, 1, "MAP_LAVARIDGE_TOWN_GYM_1F", "Lavaridge Town Gym 1F")
        add(4, 2, "MAP_LAVARIDGE_TOWN_GYM_B1F", "Lavaridge Town Gym B1F")
        add(4, 3, "MAP_LAVARIDGE_TOWN_HOUSE", "Lavaridge Town House")
        add(4, 4, "MAP_LAVARIDGE_TOWN_MART", "Lavaridge Town Mart")
        add(4, 5, "MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F", "Lavaridge Town Pokemon Center 1F")
        add(4, 6, "MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F", "Lavaridge Town Pokemon Center 2F")
        add(5, 0, "MAP_FALLARBOR_TOWN_MART", "Fallarbor Town Mart")
        add(5, 1, "MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY", "Fallarbor Town Battle Tent Lobby")
        add(5, 2, "MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR", "Fallarbor Town Battle Tent Corridor")
        add(5, 3, "MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM", "Fallarbor Town Battle Tent Battle Room")
        add(5, 4, "MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F", "Fallarbor Town Pokemon Center 1F")
        add(5, 5, "MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F", "Fallarbor Town Pokemon Center 2F")
        add(5, 6, "MAP_FALLARBOR_TOWN_COZMOS_HOUSE", "Fallarbor Town Cozmos House")
        add(5, 7, "MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE", "Fallarbor Town Move Relearners House")
        add(6, 0, "MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY", "Verdanturf Town Battle Tent Lobby")
        add(6, 1, "MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR", "Verdanturf Town Battle Tent Corridor")
        add(6, 2, "MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM", "Verdanturf Town Battle Tent Battle Room")
        add(6, 3, "MAP_VERDANTURF_TOWN_MART", "Verdanturf Town Mart")
        add(6, 4, "MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F", "Verdanturf Town Pokemon Center 1F")
        add(6, 5, "MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F", "Verdanturf Town Pokemon Center 2F")
        add(6, 6, "MAP_VERDANTURF_TOWN_WANDAS_HOUSE", "Verdanturf Town Wandas House")
        add(6, 7, "MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE", "Verdanturf Town Friendship Raters House")
        add(6, 8, "MAP_VERDANTURF_TOWN_HOUSE", "Verdanturf Town House")
        add(7, 0, "MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F", "Pacifidlog Town Pokemon Center 1F")
        add(7, 1, "MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F", "Pacifidlog Town Pokemon Center 2F")
        add(7, 2, "MAP_PACIFIDLOG_TOWN_HOUSE1", "Pacifidlog Town House 1")
        add(7, 3, "MAP_PACIFIDLOG_TOWN_HOUSE2", "Pacifidlog Town House 2")
        add(7, 4, "MAP_PACIFIDLOG_TOWN_HOUSE3", "Pacifidlog Town House 3")
        add(7, 5, "MAP_PACIFIDLOG_TOWN_HOUSE4", "Pacifidlog Town House 4")
        add(7, 6, "MAP_PACIFIDLOG_TOWN_HOUSE5", "Pacifidlog Town House 5")
        add(8, 0, "MAP_PETALBURG_CITY_WALLYS_HOUSE", "Petalburg City Wallys House")
        add(8, 1, "MAP_PETALBURG_CITY_GYM", "Petalburg City Gym")
        add(8, 2, "MAP_PETALBURG_CITY_HOUSE1", "Petalburg City House 1")
        add(8, 3, "MAP_PETALBURG_CITY_HOUSE2", "Petalburg City House 2")
        add(8, 4, "MAP_PETALBURG_CITY_POKEMON_CENTER_1F", "Petalburg City Pokemon Center 1F")
        add(8, 5, "MAP_PETALBURG_CITY_POKEMON_CENTER_2F", "Petalburg City Pokemon Center 2F")
        add(8, 6, "MAP_PETALBURG_CITY_MART", "Petalburg City Mart")
        add(9, 0, "MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F", "Slateport City Sterns Shipyard 1F")
        add(9, 1, "MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F", "Slateport City Sterns Shipyard 2F")
        add(9, 2, "MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY", "Slateport City Battle Tent Lobby")
        add(9, 3, "MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR", "Slateport City Battle Tent Corridor")
        add(9, 4, "MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM", "Slateport City Battle Tent Battle Room")
        add(9, 5, "MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE", "Slateport City Name Raters House")
        add(9, 6, "MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB", "Slateport City Pokemon Fan Club")
        add(9, 7, "MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F", "Slateport City Oceanic Museum 1F")
        add(9, 8, "MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F", "Slateport City Oceanic Museum 2F")
        add(9, 9, "MAP_SLATEPORT_CITY_HARBOR", "Slateport City Harbor")
        add(9, 10, "MAP_SLATEPORT_CITY_HOUSE", "Slateport City House")
        add(9, 11, "MAP_SLATEPORT_CITY_POKEMON_CENTER_1F", "Slateport City Pokemon Center 1F")
        add(9, 12, "MAP_SLATEPORT_CITY_POKEMON_CENTER_2F", "Slateport City Pokemon Center 2F")
        add(9, 13, "MAP_SLATEPORT_CITY_MART", "Slateport City Mart")
        add(10, 0, "MAP_MAUVILLE_CITY_GYM", "Mauville City Gym")
        add(10, 1, "MAP_MAUVILLE_CITY_BIKE_SHOP", "Mauville City Bike Shop")
        add(10, 2, "MAP_MAUVILLE_CITY_HOUSE1", "Mauville City House 1")
        add(10, 3, "MAP_MAUVILLE_CITY_GAME_CORNER", "Mauville City Game Corner")
        add(10, 4, "MAP_MAUVILLE_CITY_HOUSE2", "Mauville City House 2")
        add(10, 5, "MAP_MAUVILLE_CITY_POKEMON_CENTER_1F", "Mauville City Pokemon Center 1F")
        add(10, 6, "MAP_MAUVILLE_CITY_POKEMON_CENTER_2F", "Mauville City Pokemon Center 2F")
        add(10, 7, "MAP_MAUVILLE_CITY_MART", "Mauville City Mart")
        add(11, 0, "MAP_RUSTBORO_CITY_DEVON_CORP_1F", "Rustboro City Devon Corp 1F")
        add(11, 1, "MAP_RUSTBORO_CITY_DEVON_CORP_2F", "Rustboro City Devon Corp 2F")
        add(11, 2, "MAP_RUSTBORO_CITY_DEVON_CORP_3F", "Rustboro City Devon Corp 3F")
        add(11, 3, "MAP_RUSTBORO_CITY_GYM", "Rustboro City Gym")
        add(11, 4, "MAP_RUSTBORO_CITY_POKEMON_SCHOOL", "Rustboro City Pokemon School")
        add(11, 5, "MAP_RUSTBORO_CITY_POKEMON_CENTER_1F", "Rustboro City Pokemon Center 1F")
        add(11, 6, "MAP_RUSTBORO_CITY_POKEMON_CENTER_2F", "Rustboro City Pokemon Center 2F")
        add(11, 7, "MAP_RUSTBORO_CITY_MART", "Rustboro City Mart")
        add(11, 8, "MAP_RUSTBORO_CITY_FLAT1_1F", "Rustboro City Flat 1 1F")
        add(11, 9, "MAP_RUSTBORO_CITY_FLAT1_2F", "Rustboro City Flat 1 2F")
        add(11, 10, "MAP_RUSTBORO_CITY_HOUSE1", "Rustboro City House 1")
        add(11, 11, "MAP_RUSTBORO_CITY_CUTTERS_HOUSE", "Rustboro City Cutters House")
        add(11, 12, "MAP_RUSTBORO_CITY_HOUSE2", "Rustboro City House 2")
        add(11, 13, "MAP_RUSTBORO_CITY_FLAT2_1F", "Rustboro City Flat 2 1F")
        add(11, 14, "MAP_RUSTBORO_CITY_FLAT2_2F", "Rustboro City Flat 2 2F")
        add(11, 15, "MAP_RUSTBORO_CITY_FLAT2_3F", "Rustboro City Flat 2 3F")
        add(11, 16, "MAP_RUSTBORO_CITY_HOUSE3", "Rustboro City House 3")
        add(12, 0, "MAP_FORTREE_CITY_HOUSE1", "Fortree City House 1")
        add(12, 1, "MAP_FORTREE_CITY_GYM", "Fortree City Gym")
        add(12, 2, "MAP_FORTREE_CITY_POKEMON_CENTER_1F", "Fortree City Pokemon Center 1F")
        add(12, 3, "MAP_FORTREE_CITY_POKEMON_CENTER_2F", "Fortree City Pokemon Center 2F")
        add(12, 4, "MAP_FORTREE_CITY_MART", "Fortree City Mart")
        add(12, 5, "MAP_FORTREE_CITY_HOUSE2", "Fortree City House 2")
        add(12, 6, "MAP_FORTREE_CITY_HOUSE3", "Fortree City House 3")
        add(12, 7, "MAP_FORTREE_CITY_HOUSE4", "Fortree City House 4")
        add(12, 8, "MAP_FORTREE_CITY_HOUSE5", "Fortree City House 5")
        add(12, 9, "MAP_FORTREE_CITY_DECORATION_SHOP", "Fortree City Decoration Shop")
        add(13, 0, "MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F", "Lilycove City Cove Lily Motel 1F")
        add(13, 1, "MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F", "Lilycove City Cove Lily Motel 2F")
        add(13, 2, "MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F", "Lilycove City Lilycove Museum 1F")
        add(13, 3, "MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F", "Lilycove City Lilycove Museum 2F")
        add(13, 4, "MAP_LILYCOVE_CITY_CONTEST_LOBBY", "Lilycove City Contest Lobby")
        add(13, 5, "MAP_LILYCOVE_CITY_CONTEST_HALL", "Lilycove City Contest Hall")
        add(13, 6, "MAP_LILYCOVE_CITY_POKEMON_CENTER_1F", "Lilycove City Pokemon Center 1F")
        add(13, 7, "MAP_LILYCOVE_CITY_POKEMON_CENTER_2F", "Lilycove City Pokemon Center 2F")
        add(13, 8, "MAP_LILYCOVE_CITY_UNUSED_MART", "Lilycove City Unused Mart")
        add(13, 9, "MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB", "Lilycove City Pokemon Trainer Fan Club")
        add(13, 10, "MAP_LILYCOVE_CITY_HARBOR", "Lilycove City Harbor")
        add(13, 11, "MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE", "Lilycove City Move Deleters House")
        add(13, 12, "MAP_LILYCOVE_CITY_HOUSE1", "Lilycove City House 1")
        add(13, 13, "MAP_LILYCOVE_CITY_HOUSE2", "Lilycove City House 2")
        add(13, 14, "MAP_LILYCOVE_CITY_HOUSE3", "Lilycove City House 3")
        add(13, 15, "MAP_LILYCOVE_CITY_HOUSE4", "Lilycove City House 4")
        add(13, 16, "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F", "Lilycove City Department Store 1F")
        add(13, 17, "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F", "Lilycove City Department Store 2F")
        add(13, 18, "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F", "Lilycove City Department Store 3F")
        add(13, 19, "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F", "Lilycove City Department Store 4F")
        add(13, 20, "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F", "Lilycove City Department Store 5F")
        add(13, 21, "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP", "Lilycove City Department Store Rooftop")
        add(13, 22, "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR", "Lilycove City Department Store Elevator")
        add(14, 0, "MAP_MOSSDEEP_CITY_GYM", "Mossdeep City Gym")
        add(14, 1, "MAP_MOSSDEEP_CITY_HOUSE1", "Mossdeep City House 1")
        add(14, 2, "MAP_MOSSDEEP_CITY_HOUSE2", "Mossdeep City House 2")
        add(14, 3, "MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F", "Mossdeep City Pokemon Center 1F")
        add(14, 4, "MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F", "Mossdeep City Pokemon Center 2F")
        add(14, 5, "MAP_MOSSDEEP_CITY_MART", "Mossdeep City Mart")
        add(14, 6, "MAP_MOSSDEEP_CITY_HOUSE3", "Mossdeep City House 3")
        add(14, 7, "MAP_MOSSDEEP_CITY_STEVENS_HOUSE", "Mossdeep City Stevens House")
        add(14, 8, "MAP_MOSSDEEP_CITY_HOUSE4", "Mossdeep City House 4")
        add(14, 9, "MAP_MOSSDEEP_CITY_SPACE_CENTER_1F", "Mossdeep City Space Center 1F")
        add(14, 10, "MAP_MOSSDEEP_CITY_SPACE_CENTER_2F", "Mossdeep City Space Center 2F")
        add(14, 11, "MAP_MOSSDEEP_CITY_GAME_CORNER_1F", "Mossdeep City Game Corner 1F")
        add(14, 12, "MAP_MOSSDEEP_CITY_GAME_CORNER_B1F", "Mossdeep City Game Corner B1F")
        add(15, 0, "MAP_SOOTOPOLIS_CITY_GYM_1F", "Sootopolis City Gym 1F")
        add(15, 1, "MAP_SOOTOPOLIS_CITY_GYM_B1F", "Sootopolis City Gym B1F")
        add(15, 2, "MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F", "Sootopolis City Pokemon Center 1F")
        add(15, 3, "MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F", "Sootopolis City Pokemon Center 2F")
        add(15, 4, "MAP_SOOTOPOLIS_CITY_MART", "Sootopolis City Mart")
        add(15, 5, "MAP_SOOTOPOLIS_CITY_HOUSE1", "Sootopolis City House 1")
        add(15, 6, "MAP_SOOTOPOLIS_CITY_HOUSE2", "Sootopolis City House 2")
        add(15, 7, "MAP_SOOTOPOLIS_CITY_HOUSE3", "Sootopolis City House 3")
        add(15, 8, "MAP_SOOTOPOLIS_CITY_HOUSE4", "Sootopolis City House 4")
        add(15, 9, "MAP_SOOTOPOLIS_CITY_HOUSE5", "Sootopolis City House 5")
        add(15, 10, "MAP_SOOTOPOLIS_CITY_HOUSE6", "Sootopolis City House 6")
        add(15, 11, "MAP_SOOTOPOLIS_CITY_HOUSE7", "Sootopolis City House 7")
        add(15, 12, "MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE", "Sootopolis City Lotad and Seedot House")
        add(15, 13, "MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F", "Sootopolis City Mystery Events House 1F")
        add(15, 14, "MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F", "Sootopolis City Mystery Events House B1F")
        add(16, 0, "MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM", "Ever Grande City Sidneys Room")
        add(16, 1, "MAP_EVER_GRANDE_CITY_PHOEBES_ROOM", "Ever Grande City Phoebes Room")
        add(16, 2, "MAP_EVER_GRANDE_CITY_GLACIAS_ROOM", "Ever Grande City Glacias Room")
        add(16, 3, "MAP_EVER_GRANDE_CITY_DRAKES_ROOM", "Ever Grande City Drakes Room")
        add(16, 4, "MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM", "Ever Grande City Champions Room")
        add(16, 5, "MAP_EVER_GRANDE_CITY_HALL1", "Ever Grande City Hall 1")
        add(16, 6, "MAP_EVER_GRANDE_CITY_HALL2", "Ever Grande City Hall 2")
        add(16, 7, "MAP_EVER_GRANDE_CITY_HALL3", "Ever Grande City Hall 3")
        add(16, 8, "MAP_EVER_GRANDE_CITY_HALL4", "Ever Grande City Hall 4")
        add(16, 9, "MAP_EVER_GRANDE_CITY_HALL5", "Ever Grande City Hall 5")
        add(16, 10, "MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F", "Ever Grande City Pokemon League 1F")
        add(16, 11, "MAP_EVER_GRANDE_CITY_HALL_OF_FAME", "Ever Grande City Hall of Fame")
        add(16, 12, "MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F", "Ever Grande City Pokemon Center 1F")
        add(16, 13, "MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F", "Ever Grande City Pokemon Center 2F")
        add(16, 14, "MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F", "Ever Grande City Pokemon League 2F")
        add(17, 0, "MAP_ROUTE104_MR_BRINEYS_HOUSE", "Route 104 Mr. Brineys House")
        add(17, 1, "MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP", "Route 104 Pretty Petal Flower Shop")
        add(18, 0, "MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE", "Route 111 Winstrate Familys House")
        add(18, 1, "MAP_ROUTE111_OLD_LADYS_REST_STOP", "Route 111 Old Ladys Rest Stop")
        add(19, 0, "MAP_ROUTE112_CABLE_CAR_STATION", "Route 112 Cable Car Station")
        add(19, 1, "MAP_MT_CHIMNEY_CABLE_CAR_STATION", "Mt. Chimney Cable Car Station")
        add(20, 0, "MAP_ROUTE114_FOSSIL_MANIACS_HOUSE", "Route 114 Fossil Maniacs House")
        add(20, 1, "MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL", "Route 114 Fossil Maniacs Tunnel")
        add(20, 2, "MAP_ROUTE114_LANETTES_HOUSE", "Route 114 Lanettes House")
        add(21, 0, "MAP_ROUTE116_TUNNELERS_REST_HOUSE", "Route 116 Tunnelers Rest House")
        add(22, 0, "MAP_ROUTE117_POKEMON_DAY_CARE", "Route 117 Pokemon Day Care")
        add(23, 0, "MAP_ROUTE121_SAFARI_ZONE_ENTRANCE", "Route 121 Safari Zone Entrance")
        add(24, 0, "MAP_METEOR_FALLS_1F_1R", "Meteor Falls 1F 1R")
        add(24, 1, "MAP_METEOR_FALLS_1F_2R", "Meteor Falls 1F 2R")
        add(24, 2, "MAP_METEOR_FALLS_B1F_1R", "Meteor Falls B1F 1R")
        add(24, 3, "MAP_METEOR_FALLS_B1F_2R", "Meteor Falls B1F 2R")
        add(24, 4, "MAP_RUSTURF_TUNNEL", "Rusturf Tunnel")
        add(24, 5, "MAP_UNDERWATER_SOOTOPOLIS_CITY", "Underwater Sootopolis City")
        add(24, 6, "MAP_DESERT_RUINS", "Desert Ruins")
        add(24, 7, "MAP_GRANITE_CAVE_1F", "Granite Cave 1F")
        add(24, 8, "MAP_GRANITE_CAVE_B1F", "Granite Cave B1F")
        add(24, 9, "MAP_GRANITE_CAVE_B2F", "Granite Cave B2F")
        add(24, 10, "MAP_GRANITE_CAVE_STEVENS_ROOM", "Granite Cave Stevens Room")
        add(24, 11, "MAP_PETALBURG_WOODS", "Petalburg Woods")
        add(24, 12, "MAP_MT_CHIMNEY", "Mt. Chimney")
        add(24, 13, "MAP_JAGGED_PASS", "Jagged Pass")
        add(24, 14, "MAP_FIERY_PATH", "Fiery Path")
        add(24, 15, "MAP_MT_PYRE_1F", "Mt. Pyre 1F")
        add(24, 16, "MAP_MT_PYRE_2F", "Mt. Pyre 2F")
        add(24, 17, "MAP_MT_PYRE_3F", "Mt. Pyre 3F")
        add(24, 18, "MAP_MT_PYRE_4F", "Mt. Pyre 4F")
        add(24, 19, "MAP_MT_PYRE_5F", "Mt. Pyre 5F")
        add(24, 20, "MAP_MT_PYRE_6F", "Mt. Pyre 6F")
        add(24, 21, "MAP_MT_PYRE_EXTERIOR", "Mt. Pyre Exterior")
        add(24, 22, "MAP_MT_PYRE_SUMMIT", "Mt. Pyre Summit")
        add(24, 23, "MAP_AQUA_HIDEOUT_1F", "Aqua Hideout 1F")
        add(24, 24, "MAP_AQUA_HIDEOUT_B1F", "Aqua Hideout B1F")
        add(24, 25, "MAP_AQUA_HIDEOUT_B2F", "Aqua Hideout B2F")
        add(24, 26, "MAP_UNDERWATER_SEAFLOOR_CAVERN", "Underwater Seafloor Cavern")
        add(24, 27, "MAP_SEAFLOOR_CAVERN_ENTRANCE", "Seafloor Cavern Entrance")
        add(24, 28, "MAP_SEAFLOOR_CAVERN_ROOM1", "Seafloor Cavern Room 1")
        add(24, 29, "MAP_SEAFLOOR_CAVERN_ROOM2", "Seafloor Cavern Room 2")
        add(24, 30, "MAP_SEAFLOOR_CAVERN_ROOM3", "Seafloor Cavern Room 3")
        add(24, 31, "MAP_SEAFLOOR_CAVERN_ROOM4", "Seafloor Cavern Room 4")
        add(24, 32, "MAP_SEAFLOOR_CAVERN_ROOM5", "Seafloor Cavern Room 5")
        add(24, 33, "MAP_SEAFLOOR_CAVERN_ROOM6", "Seafloor Cavern Room 6")
        add(24, 34, "MAP_SEAFLOOR_CAVERN_ROOM7", "Seafloor Cavern Room 7")
        add(24, 35, "MAP_SEAFLOOR_CAVERN_ROOM8", "Seafloor Cavern Room 8")
        add(24, 36, "MAP_SEAFLOOR_CAVERN_ROOM9", "Seafloor Cavern Room 9")
        add(24, 37, "MAP_CAVE_OF_ORIGIN_ENTRANCE", "Cave of Origin Entrance")
        add(24, 38, "MAP_CAVE_OF_ORIGIN_1F", "Cave of Origin 1F")
        add(24, 39, "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1", "Cave of Origin Unused Ruby Sapphire Map 1")
        add(24, 40, "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2", "Cave of Origin Unused Ruby Sapphire Map 2")
        add(24, 41, "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3", "Cave of Origin Unused Ruby Sapphire Map 3")
        add(24, 42, "MAP_CAVE_OF_ORIGIN_B1F", "Cave of Origin B1F")
        add(24, 43, "MAP_VICTORY_ROAD_1F", "Victory Road 1F")
        add(24, 44, "MAP_VICTORY_ROAD_B1F", "Victory Road B1F")
        add(24, 45, "MAP_VICTORY_ROAD_B2F", "Victory Road B2F")
        add(24, 46, "MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM", "Shoal Cave Low Tide Entrance Room")
        add(24, 47, "MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM", "Shoal Cave Low Tide Inner Room")
        add(24, 48, "MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM", "Shoal Cave Low Tide Stairs Room")
        add(24, 49, "MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM", "Shoal Cave Low Tide Lower Room")
        add(24, 50, "MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM", "Shoal Cave High Tide Entrance Room")
        add(24, 51, "MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM", "Shoal Cave High Tide Inner Room")
        add(24, 52, "MAP_NEW_MAUVILLE_ENTRANCE", "New Mauville Entrance")
        add(24, 53, "MAP_NEW_MAUVILLE_INSIDE", "New Mauville Inside")
        add(24, 54, "MAP_ABANDONED_SHIP_DECK", "Abandoned Ship Deck")
        add(24, 55, "MAP_ABANDONED_SHIP_CORRIDORS_1F", "Abandoned Ship Corridors 1F")
        add(24, 56, "MAP_ABANDONED_SHIP_ROOMS_1F", "Abandoned Ship Rooms 1F")
        add(24, 57, "MAP_ABANDONED_SHIP_CORRIDORS_B1F", "Abandoned Ship Corridors B1F")
        add(24, 58, "MAP_ABANDONED_SHIP_ROOMS_B1F", "Abandoned Ship Rooms B1F")
        add(24, 59, "MAP_ABANDONED_SHIP_ROOMS2_B1F", "Abandoned Ship Rooms 2 B1F")
        add(24, 60, "MAP_ABANDONED_SHIP_UNDERWATER1", "Abandoned Ship Underwater 1")
        add(24, 61, "MAP_ABANDONED_SHIP_ROOM_B1F", "Abandoned Ship Room B1F")
        add(24, 62, "MAP_ABANDONED_SHIP_ROOMS2_1F", "Abandoned Ship Rooms 2 1F")
        add(24, 63, "MAP_ABANDONED_SHIP_CAPTAINS_OFFICE", "Abandoned Ship Captains Office")
        add(24, 64, "MAP_ABANDONED_SHIP_UNDERWATER2", "Abandoned Ship Underwater 2")
        add(24, 65, "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", "Abandoned Ship Hidden Floor Corridors")
        add(24, 66, "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS", "Abandoned Ship Hidden Floor Rooms")
        add(24, 67, "MAP_ISLAND_CAVE", "Island Cave")
        add(24, 68, "MAP_ANCIENT_TOMB", "Ancient Tomb")
        add(24, 69, "MAP_UNDERWATER_ROUTE134", "Underwater Route 134")
        add(24, 70, "MAP_UNDERWATER_SEALED_CHAMBER", "Underwater Sealed Chamber")
        add(24, 71, "MAP_SEALED_CHAMBER_OUTER_ROOM", "Sealed Chamber Outer Room")
        add(24, 72, "MAP_SEALED_CHAMBER_INNER_ROOM", "Sealed Chamber Inner Room")
        add(24, 73, "MAP_SCORCHED_SLAB", "Scorched Slab")
        add(24, 74, "MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1", "Aqua Hideout Unused Ruby Map 1")
        add(24, 75, "MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2", "Aqua Hideout Unused Ruby Map 2")
        add(24, 76, "MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3", "Aqua Hideout Unused Ruby Map 3")
        add(24, 77, "MAP_SKY_PILLAR_ENTRANCE", "Sky Pillar Entrance")
        add(24, 78, "MAP_SKY_PILLAR_OUTSIDE", "Sky Pillar Outside")
        add(24, 79, "MAP_SKY_PILLAR_1F", "Sky Pillar 1F")
        add(24, 80, "MAP_SKY_PILLAR_2F", "Sky Pillar 2F")
        add(24, 81, "MAP_SKY_PILLAR_3F", "Sky Pillar 3F")
        add(24, 82, "MAP_SKY_PILLAR_4F", "Sky Pillar 4F")
        add(24, 83, "MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM", "Shoal Cave Low Tide Ice Room")
        add(24, 84, "MAP_SKY_PILLAR_5F", "Sky Pillar 5F")
        add(24, 85, "MAP_SKY_PILLAR_TOP", "Sky Pillar Top")
        add(24, 86, "MAP_MAGMA_HIDEOUT_1F", "Magma Hideout 1F")
        add(24, 87, "MAP_MAGMA_HIDEOUT_2F_1R", "Magma Hideout 2F 1R")
        add(24, 88, "MAP_MAGMA_HIDEOUT_2F_2R", "Magma Hideout 2F 2R")
        add(24, 89, "MAP_MAGMA_HIDEOUT_3F_1R", "Magma Hideout 3F 1R")
        add(24, 90, "MAP_MAGMA_HIDEOUT_3F_2R", "Magma Hideout 3F 2R")
        add(24, 91, "MAP_MAGMA_HIDEOUT_4F", "Magma Hideout 4F")
        add(24, 92, "MAP_MAGMA_HIDEOUT_3F_3R", "Magma Hideout 3F 3R")
        add(24, 93, "MAP_MAGMA_HIDEOUT_2F_3R", "Magma Hideout 2F 3R")
        add(24, 94, "MAP_MIRAGE_TOWER_1F", "Mirage Tower 1F")
        add(24, 95, "MAP_MIRAGE_TOWER_2F", "Mirage Tower 2F")
        add(24, 96, "MAP_MIRAGE_TOWER_3F", "Mirage Tower 3F")
        add(24, 97, "MAP_MIRAGE_TOWER_4F", "Mirage Tower 4F")
        add(24, 98, "MAP_DESERT_UNDERPASS", "Desert Underpass")
        add(24, 99, "MAP_ARTISAN_CAVE_B1F", "Artisan Cave B1F")
        add(24, 100, "MAP_ARTISAN_CAVE_1F", "Artisan Cave 1F")
        add(24, 101, "MAP_UNDERWATER_MARINE_CAVE", "Underwater Marine Cave")
        add(24, 102, "MAP_MARINE_CAVE_ENTRANCE", "Marine Cave Entrance")
        add(24, 103, "MAP_MARINE_CAVE_END", "Marine Cave End")
        add(24, 104, "MAP_TERRA_CAVE_ENTRANCE", "Terra Cave Entrance")
        add(24, 105, "MAP_TERRA_CAVE_END", "Terra Cave End")
        add(24, 106, "MAP_ALTERING_CAVE", "Altering Cave")
        add(24, 107, "MAP_METEOR_FALLS_STEVENS_CAVE", "Meteor Falls Stevens Cave")
        add(25, 0, "MAP_SECRET_BASE_RED_CAVE1", "Secret Base Red Cave 1")
        add(25, 1, "MAP_SECRET_BASE_BROWN_CAVE1", "Secret Base Brown Cave 1")
        add(25, 2, "MAP_SECRET_BASE_BLUE_CAVE1", "Secret Base Blue Cave 1")
        add(25, 3, "MAP_SECRET_BASE_YELLOW_CAVE1", "Secret Base Yellow Cave 1")
        add(25, 4, "MAP_SECRET_BASE_TREE1", "Secret Base Tree 1")
        add(25, 5, "MAP_SECRET_BASE_SHRUB1", "Secret Base Shrub 1")
        add(25, 6, "MAP_SECRET_BASE_RED_CAVE2", "Secret Base Red Cave 2")
        add(25, 7, "MAP_SECRET_BASE_BROWN_CAVE2", "Secret Base Brown Cave 2")
        add(25, 8, "MAP_SECRET_BASE_BLUE_CAVE2", "Secret Base Blue Cave 2")
        add(25, 9, "MAP_SECRET_BASE_YELLOW_CAVE2", "Secret Base Yellow Cave 2")
        add(25, 10, "MAP_SECRET_BASE_TREE2", "Secret Base Tree 2")
        add(25, 11, "MAP_SECRET_BASE_SHRUB2", "Secret Base Shrub 2")
        add(25, 12, "MAP_SECRET_BASE_RED_CAVE3", "Secret Base Red Cave 3")
        add(25, 13, "MAP_SECRET_BASE_BROWN_CAVE3", "Secret Base Brown Cave 3")
        add(25, 14, "MAP_SECRET_BASE_BLUE_CAVE3", "Secret Base Blue Cave 3")
        add(25, 15, "MAP_SECRET_BASE_YELLOW_CAVE3", "Secret Base Yellow Cave 3")
        add(25, 16, "MAP_SECRET_BASE_TREE3", "Secret Base Tree 3")
        add(25, 17, "MAP_SECRET_BASE_SHRUB3", "Secret Base Shrub 3")
        add(25, 18, "MAP_SECRET_BASE_RED_CAVE4", "Secret Base Red Cave 4")
        add(25, 19, "MAP_SECRET_BASE_BROWN_CAVE4", "Secret Base Brown Cave 4")
        add(25, 20, "MAP_SECRET_BASE_BLUE_CAVE4", "Secret Base Blue Cave 4")
        add(25, 21, "MAP_SECRET_BASE_YELLOW_CAVE4", "Secret Base Yellow Cave 4")
        add(25, 22, "MAP_SECRET_BASE_TREE4", "Secret Base Tree 4")
        add(25, 23, "MAP_SECRET_BASE_SHRUB4", "Secret Base Shrub 4")
        add(25, 24, "MAP_BATTLE_COLOSSEUM_2P", "Battle Colosseum 2P")
        add(25, 25, "MAP_TRADE_CENTER", "Trade Center")
        add(25, 26, "MAP_RECORD_CORNER", "Record Corner")
        add(25, 27, "MAP_BATTLE_COLOSSEUM_4P", "Battle Colosseum 4P")
        add(25, 28, "MAP_CONTEST_HALL", "Contest Hall")
        add(25, 29, "MAP_UNUSED_CONTEST_HALL1", "Unused Contest Hall 1")
        add(25, 30, "MAP_UNUSED_CONTEST_HALL2", "Unused Contest Hall 2")
        add(25, 31, "MAP_UNUSED_CONTEST_HALL3", "Unused Contest Hall 3")
        add(25, 32, "MAP_UNUSED_CONTEST_HALL4", "Unused Contest Hall 4")
        add(25, 33, "MAP_UNUSED_CONTEST_HALL5", "Unused Contest Hall 5")
        add(25, 34, "MAP_UNUSED_CONTEST_HALL6", "Unused Contest Hall 6")
        add(25, 35, "MAP_CONTEST_HALL_BEAUTY", "Contest Hall Beauty")
        add(25, 36, "MAP_CONTEST_HALL_TOUGH", "Contest Hall Tough")
        add(25, 37, "MAP_CONTEST_HALL_COOL", "Contest Hall Cool")
        add(25, 38, "MAP_CONTEST_HALL_SMART", "Contest Hall Smart")
        add(25, 39, "MAP_CONTEST_HALL_CUTE", "Contest Hall Cute")
        add(25, 40, "MAP_INSIDE_OF_TRUCK", "Inside of Truck")
        add(25, 41, "MAP_SS_TIDAL_CORRIDOR", "S.S. Tidal Corridor")
        add(25, 42, "MAP_SS_TIDAL_LOWER_DECK", "S.S. Tidal Lower Deck")
        add(25, 43, "MAP_SS_TIDAL_ROOMS", "S.S. Tidal Rooms")
        add(25, 44, "MAP_BATTLE_PYRAMID_SQUARE01", "Battle Pyramid Square 01")
        add(25, 45, "MAP_BATTLE_PYRAMID_SQUARE02", "Battle Pyramid Square 02")
        add(25, 46, "MAP_BATTLE_PYRAMID_SQUARE03", "Battle Pyramid Square 03")
        add(25, 47, "MAP_BATTLE_PYRAMID_SQUARE04", "Battle Pyramid Square 04")
        add(25, 48, "MAP_BATTLE_PYRAMID_SQUARE05", "Battle Pyramid Square 05")
        add(25, 49, "MAP_BATTLE_PYRAMID_SQUARE06", "Battle Pyramid Square 06")
        add(25, 50, "MAP_BATTLE_PYRAMID_SQUARE07", "Battle Pyramid Square 07")
        add(25, 51, "MAP_BATTLE_PYRAMID_SQUARE08", "Battle Pyramid Square 08")
        add(25, 52, "MAP_BATTLE_PYRAMID_SQUARE09", "Battle Pyramid Square 09")
        add(25, 53, "MAP_BATTLE_PYRAMID_SQUARE10", "Battle Pyramid Square 10")
        add(25, 54, "MAP_BATTLE_PYRAMID_SQUARE11", "Battle Pyramid Square 11")
        add(25, 55, "MAP_BATTLE_PYRAMID_SQUARE12", "Battle Pyramid Square 12")
        add(25, 56, "MAP_BATTLE_PYRAMID_SQUARE13", "Battle Pyramid Square 13")
        add(25, 57, "MAP_BATTLE_PYRAMID_SQUARE14", "Battle Pyramid Square 14")
        add(25, 58, "MAP_BATTLE_PYRAMID_SQUARE15", "Battle Pyramid Square 15")
        add(25, 59, "MAP_BATTLE_PYRAMID_SQUARE16", "Battle Pyramid Square 16")
        add(25, 60, "MAP_UNION_ROOM", "Union Room")
        add(26, 0, "MAP_SAFARI_ZONE_NORTHWEST", "Safari Zone Northwest")
        add(26, 1, "MAP_SAFARI_ZONE_NORTH", "Safari Zone North")
        add(26, 2, "MAP_SAFARI_ZONE_SOUTHWEST", "Safari Zone Southwest")
        add(26, 3, "MAP_SAFARI_ZONE_SOUTH", "Safari Zone South")
        add(26, 4, "MAP_BATTLE_FRONTIER_OUTSIDE_WEST", "Battle Frontier Outside West")
        add(26, 5, "MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY", "Battle Frontier Battle Tower Lobby")
        add(26, 6, "MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR", "Battle Frontier Battle Tower Elevator")
        add(26, 7, "MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR", "Battle Frontier Battle Tower Corridor")
        add(26, 8, "MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM", "Battle Frontier Battle Tower Battle Room")
        add(26, 9, "MAP_SOUTHERN_ISLAND_EXTERIOR", "Southern Island Exterior")
        add(26, 10, "MAP_SOUTHERN_ISLAND_INTERIOR", "Southern Island Interior")
        add(26, 11, "MAP_SAFARI_ZONE_REST_HOUSE", "Safari Zone Rest House")
        add(26, 12, "MAP_SAFARI_ZONE_NORTHEAST", "Safari Zone Northeast")
        add(26, 13, "MAP_SAFARI_ZONE_SOUTHEAST", "Safari Zone Southeast")
        add(26, 14, "MAP_BATTLE_FRONTIER_OUTSIDE_EAST", "Battle Frontier Outside East")
        add(26, 15, "MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM", "Battle Frontier Battle Tower Multi Partner Room")
        add(26, 16, "MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR", "Battle Frontier Battle Tower Multi Corridor")
        add(26, 17, "MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM", "Battle Frontier Battle Tower Multi Battle Room")
        add(26, 18, "MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY", "Battle Frontier Battle Dome Lobby")
        add(26, 19, "MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR", "Battle Frontier Battle Dome Corridor")
        add(26, 20, "MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM", "Battle Frontier Battle Dome Pre Battle Room")
        add(26, 21, "MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM", "Battle Frontier Battle Dome Battle Room")
        add(26, 22, "MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY", "Battle Frontier Battle Palace Lobby")
        add(26, 23, "MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR", "Battle Frontier Battle Palace Corridor")
        add(26, 24, "MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM", "Battle Frontier Battle Palace Battle Room")
        add(26, 25, "MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY", "Battle Frontier Battle Pyramid Lobby")
        add(26, 26, "MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR", "Battle Frontier Battle Pyramid Floor")
        add(26, 27, "MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP", "Battle Frontier Battle Pyramid Top")
        add(26, 28, "MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY", "Battle Frontier Battle Arena Lobby")
        add(26, 29, "MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR", "Battle Frontier Battle Arena Corridor")
        add(26, 30, "MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM", "Battle Frontier Battle Arena Battle Room")
        add(26, 31, "MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY", "Battle Frontier Battle Factory Lobby")
        add(26, 32, "MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM", "Battle Frontier Battle Factory Pre Battle Room")
        add(26, 33, "MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM", "Battle Frontier Battle Factory Battle Room")
        add(26, 34, "MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY", "Battle Frontier Battle Pike Lobby")
        add(26, 35, "MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR", "Battle Frontier Battle Pike Corridor")
        add(26, 36, "MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM", "Battle Frontier Battle Pike Three Path Room")
        add(26, 37, "MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL", "Battle Frontier Battle Pike Room Normal")
        add(26, 38, "MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL", "Battle Frontier Battle Pike Room Final")
        add(26, 39, "MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS", "Battle Frontier Battle Pike Room Wild Mons")
        add(26, 40, "MAP_BATTLE_FRONTIER_RANKING_HALL", "Battle Frontier Ranking Hall")
        add(26, 41, "MAP_BATTLE_FRONTIER_LOUNGE1", "Battle Frontier Lounge 1")
        add(26, 42, "MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER", "Battle Frontier Exchange Service Corner")
        add(26, 43, "MAP_BATTLE_FRONTIER_LOUNGE2", "Battle Frontier Lounge 2")
        add(26, 44, "MAP_BATTLE_FRONTIER_LOUNGE3", "Battle Frontier Lounge 3")
        add(26, 45, "MAP_BATTLE_FRONTIER_LOUNGE4", "Battle Frontier Lounge 4")
        add(26, 46, "MAP_BATTLE_FRONTIER_SCOTTS_HOUSE", "Battle Frontier Scotts House")
        add(26, 47, "MAP_BATTLE_FRONTIER_LOUNGE5", "Battle Frontier Lounge 5")
        add(26, 48, "MAP_BATTLE_FRONTIER_LOUNGE6", "Battle Frontier Lounge 6")
        add(26, 49, "MAP_BATTLE_FRONTIER_LOUNGE7", "Battle Frontier Lounge 7")
        add(26, 50, "MAP_BATTLE_FRONTIER_RECEPTION_GATE", "Battle Frontier Reception Gate")
        add(26, 51, "MAP_BATTLE_FRONTIER_LOUNGE8", "Battle Frontier Lounge 8")
        add(26, 52, "MAP_BATTLE_FRONTIER_LOUNGE9", "Battle Frontier Lounge 9")
        add(26, 53, "MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F", "Battle Frontier Pokemon Center 1F")
        add(26, 54, "MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F", "Battle Frontier Pokemon Center 2F")
        add(26, 55, "MAP_BATTLE_FRONTIER_MART", "Battle Frontier Mart")
        add(26, 56, "MAP_FARAWAY_ISLAND_ENTRANCE", "Faraway Island Entrance")
        add(26, 57, "MAP_FARAWAY_ISLAND_INTERIOR", "Faraway Island Interior")
        add(26, 58, "MAP_BIRTH_ISLAND_EXTERIOR", "Birth Island Exterior")
        add(26, 59, "MAP_BIRTH_ISLAND_HARBOR", "Birth Island Harbor")
        add(26, 60, "MAP_TRAINER_HILL_ENTRANCE", "Trainer Hill Entrance")
        add(26, 61, "MAP_TRAINER_HILL_1F", "Trainer Hill 1F")
        add(26, 62, "MAP_TRAINER_HILL_2F", "Trainer Hill 2F")
        add(26, 63, "MAP_TRAINER_HILL_3F", "Trainer Hill 3F")
        add(26, 64, "MAP_TRAINER_HILL_4F", "Trainer Hill 4F")
        add(26, 65, "MAP_TRAINER_HILL_ROOF", "Trainer Hill Roof")
        add(26, 66, "MAP_NAVEL_ROCK_EXTERIOR", "Navel Rock Exterior")
        add(26, 67, "MAP_NAVEL_ROCK_HARBOR", "Navel Rock Harbor")
        add(26, 68, "MAP_NAVEL_ROCK_ENTRANCE", "Navel Rock Entrance")
        add(26, 69, "MAP_NAVEL_ROCK_B1F", "Navel Rock B1F")
        add(26, 70, "MAP_NAVEL_ROCK_FORK", "Navel Rock Fork")
        add(26, 71, "MAP_NAVEL_ROCK_UP1", "Navel Rock Up 1")
        add(26, 72, "MAP_NAVEL_ROCK_UP2", "Navel Rock Up 2")
        add(26, 73, "MAP_NAVEL_ROCK_UP3", "Navel Rock Up 3")
        add(26, 74, "MAP_NAVEL_ROCK_UP4", "Navel Rock Up 4")
        add(26, 75, "MAP_NAVEL_ROCK_TOP", "Navel Rock Top")
        add(26, 76, "MAP_NAVEL_ROCK_DOWN01", "Navel Rock Down 01")
        add(26, 77, "MAP_NAVEL_ROCK_DOWN02", "Navel Rock Down 02")
        add(26, 78, "MAP_NAVEL_ROCK_DOWN03", "Navel Rock Down 03")
        add(26, 79, "MAP_NAVEL_ROCK_DOWN04", "Navel Rock Down 04")
        add(26, 80, "MAP_NAVEL_ROCK_DOWN05", "Navel Rock Down 05")
        add(26, 81, "MAP_NAVEL_ROCK_DOWN06", "Navel Rock Down 06")
        add(26, 82, "MAP_NAVEL_ROCK_DOWN07", "Navel Rock Down 07")
        add(26, 83, "MAP_NAVEL_ROCK_DOWN08", "Navel Rock Down 08")
        add(26, 84, "MAP_NAVEL_ROCK_DOWN09", "Navel Rock Down 09")
        add(26, 85, "MAP_NAVEL_ROCK_DOWN10", "Navel Rock Down 10")
        add(26, 86, "MAP_NAVEL_ROCK_DOWN11", "Navel Rock Down 11")
        add(26, 87, "MAP_NAVEL_ROCK_BOTTOM", "Navel Rock Bottom")
        add(26, 88, "MAP_TRAINER_HILL_ELEVATOR", "Trainer Hill Elevator")
        add(27, 0, "MAP_ROUTE104_PROTOTYPE", "Route 104 Prototype")
        add(27, 1, "MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP", "Route 104 Prototype Pretty Petal Flower Shop")
        add(28, 0, "MAP_ROUTE109_SEASHORE_HOUSE", "Route 109 Seashore House")
        add(29, 0, "MAP_ROUTE110_TRICK_HOUSE_ENTRANCE", "Route 110 Trick House Entrance")
        add(29, 1, "MAP_ROUTE110_TRICK_HOUSE_END", "Route 110 Trick House End")
        add(29, 2, "MAP_ROUTE110_TRICK_HOUSE_CORRIDOR", "Route 110 Trick House Corridor")
        add(29, 3, "MAP_ROUTE110_TRICK_HOUSE_PUZZLE1", "Route 110 Trick House Puzzle 1")
        add(29, 4, "MAP_ROUTE110_TRICK_HOUSE_PUZZLE2", "Route 110 Trick House Puzzle 2")
        add(29, 5, "MAP_ROUTE110_TRICK_HOUSE_PUZZLE3", "Route 110 Trick House Puzzle 3")
        add(29, 6, "MAP_ROUTE110_TRICK_HOUSE_PUZZLE4", "Route 110 Trick House Puzzle 4")
        add(29, 7, "MAP_ROUTE110_TRICK_HOUSE_PUZZLE5", "Route 110 Trick House Puzzle 5")
        add(29, 8, "MAP_ROUTE110_TRICK_HOUSE_PUZZLE6", "Route 110 Trick House Puzzle 6")
        add(29, 9, "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7", "Route 110 Trick House Puzzle 7")
        add(29, 10, "MAP_ROUTE110_TRICK_HOUSE_PUZZLE8", "Route 110 Trick House Puzzle 8")
        add(29, 11, "MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE", "Route 110 Seaside Cycling Road South Entrance")
        add(29, 12, "MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE", "Route 110 Seaside Cycling Road North Entrance")
        add(30, 0, "MAP_ROUTE113_GLASS_WORKSHOP", "Route 113 Glass Workshop")
        add(31, 0, "MAP_ROUTE123_BERRY_MASTERS_HOUSE", "Route 123 Berry Masters House")
        add(32, 0, "MAP_ROUTE119_WEATHER_INSTITUTE_1F", "Route 119 Weather Institute 1F")
        add(32, 1, "MAP_ROUTE119_WEATHER_INSTITUTE_2F", "Route 119 Weather Institute 2F")
        add(32, 2, "MAP_ROUTE119_HOUSE", "Route 119 House")
        add(33, 0, "MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE", "Route 124 Diving Treasure Hunters House")

    }

    private fun MutableMap<Pair<Int, Int>, EmeraldMap>.add(group: Int, number: Int, id: String, name: String) {
        put(group to number, EmeraldMap(id, displayName(name)))
    }

    private fun displayName(name: String): String = when {
        name.startsWith("Route ") -> name.replace("Route ", "Ruta ")
        name == "Petalburg City" -> "Ciudad Petalburg"
        name == "Slateport City" -> "Ciudad Portual"
        name == "Mauville City" -> "Ciudad Malvalona"
        name == "Rustboro City" -> "Ciudad Férrica"
        name == "Littleroot Town" -> "Pueblo Raíz"
        name == "Oldale Town" -> "Pueblo Escaso"
        name == "Dewford Town" -> "Pueblo Azuliza"
        name == "Lavaridge Town" -> "Pueblo Lavacalda"
        name == "Fallarbor Town" -> "Pueblo Pardal"
        name == "Verdanturf Town" -> "Pueblo Verdegal"
        name == "Pacifidlog Town" -> "Pueblo Oromar"
        else -> name
    }

    fun resolveMapId(mapGroup: Int, mapNumber: Int): EmeraldMap = entries[mapGroup to mapNumber]
        ?: EmeraldMap("UNKNOWN_GROUP_${mapGroup}_MAP_${mapNumber}", "Mapa desconocido ($mapGroup:$mapNumber)")

    fun fromMemoryValue(value: Int): EmeraldMap = resolveMapId((value ushr 8) and 0xFF, value and 0xFF)
}
